### ISSUE TITLE
Potentials Not Changing Value

### ISSUE THREAD

**Issue by chismgr** [ksucpea/bettercanvas#1]
The potentials for me never change. They are always at 0.00% no matter what happens with my grades.

**Comment by ksucpea** [comment]
Assignment potentials were kind of an expiermental thing I was trying out and wasn't able to test on other canvas accounts. Is there anyway I could contact you to get more info and solve this?

**Comment by chismgr** [comment]
Sure! I'd be happy to help. I'm new to git, is there any sort of direct messaging?

**Comment by ksucpea** [comment]
Got rid of this feature so I'm closing this issue. Had a lot of problems and not sure how many people actually used it anway
