### ISSUE TITLE
Quiz assignments in dashboard fails to load

### ISSUE THREAD

**Issue by Jelgnum** [ksucpea/bettercanvas#11]
Browser: Firefox v104.0.1

When clicking the link for a assignment under a class in dashboard the link fails if the the assignment is a Quiz
![image](https://user-images.githubusercontent.com/86729439/188532775-42808e59-04d1-45b4-9cf0-69912f15b189.png)

takes me to this link, which is a Page not found
![image](https://user-images.githubusercontent.com/86729439/188533021-cb7265d9-a435-419b-b6ec-640f2cd208b5.png)

While that link is the same as the one I see when hovering over the assignment in the assignments tab the one that shows up when on the assignment ends like this
![image](https://user-images.githubusercontent.com/86729439/188533360-c848b605-c388-4507-8f1f-16a335d4f2ef.png)

Normal assignments under the assignments tab work fine when clicked

**Comment by ksucpea** [comment]
Thanks for letting me know about this, should be an easy fix, I’ll get to
work on it

**Comment by Jelgnum** [comment]
fixed with [5e35f70](https://github.com/ksucpea/bettercanvas/commit/5e35f70cb2489fd3146c814c81689746ab901f99)
thanks
