### ISSUE TITLE
BetterCanvas unavailable for Firefox

### ISSUE THREAD

**Issue by AsadSolos** [ksucpea/bettercanvas#13]
Pretty self-explanatory. The extension was removed from Firefox. Is it possible to upload the raw extension file/reupload it?
![Screen Shot 2022-09-22 at 5 02 27 PM](https://user-images.githubusercontent.com/114190780/191850416-f60900a2-0c42-44fd-9e09-65d682cf8811.png)

**Comment by ksucpea** [comment]
I'm in the process of fixing this, but addons is just being kind of weird with their review process. In the mean time you can download the firefox branch and load the extension into firefox yourself from here https://github.com/ksucpea/bettercanvas/tree/firefox

**Comment by AsadSolos** [comment]
Alright, will do. Thanks

**Comment by AsadSolos** [comment]
I fixed the extension. You were missing the ID which is required for it to be added, at least in a developer version of Firefox with Signature Verification off. Gonna upload the zip file, it's like 4 lines of code that needed to be changed. For the domain email thing I made it better@canvas.com if that's cool.

**Comment by ksucpea** [comment]
From my understanding, those 4 lines get added automatically when I upload the addon. They said they disabled the addon because it's "creating DOM nodes using potentially unsanitzed data from innerHTML", which is not the case. I don't use any unsanitzed data with innerHTML

**Comment by ksucpea** [comment]
Extension is back up on firefox if you'd like to install that instead
