### ISSUE TITLE
Exclude specific website

### ISSUE THREAD

**Issue by Perry2004** [ksucpea/bettercanvas#14]
When opening external websites related to canvas (zybooks, in my case, an online platform for programming), contents on these pages are also (partially) darkened by the extension. 

It's bizarre because on these sites only part of the contents is darkened, and I want only the canvas pages to be dimmed. Are there anyways that I can exclude canvas-related, but not canvas, websites from being darkened?

**Comment by ksucpea** [comment]
Hey there, can you try setting a custom url in the extension popup menu and see if that helps?

**Comment by Perry2004** [comment]
That successfully resolved the problem. Now only the canvas page is darkened. 
Thanks for your answer.
