### ISSUE TITLE
js issue for specifically my school's canvas

### ISSUE THREAD

**Issue by Solenyy27** [ksucpea/bettercanvas#15]
Hi, coding noob here. My school's version of canvas doesn't have canvas actually written in the domain (webcourses.ucf.edu) so the function that checks to see if the page displayed is a canvas page doesn't work for me. I manually forked, downloded, changed, verified, and installed a modified version of this with just that field changed and it works fine now. 

Also the column that has the home, modules, etc. tabs is still blaringly white for me, I think ic-Layout-columns needs to be included somewhere but, as meantioned, I'm new to this and couldn't get it to work.

**Comment by ksucpea** [comment]
Ok cool I'll see if I can fix that white element. What url are you using for the custom url? I think everyone who has had an issue with it had a trailing slash at the end which was causing the error. If that's not your problem, try typing https:// into the custom url and let me know if that still doesn't work

**Comment by Solenyy27** [comment]
ah yup, trailing slash did it lol. White element still there on the non-altered version. Thanks, this is a great lil plugin and it was fun to poke through the code.

**Comment by ksucpea** [comment]
Great, I will add the white element fix in the next update and we'll see if it works for you

**Comment by ksucpea** [comment]
Update was published today, can you let me know if it fixed this?

**Comment by probablypablito** [comment]
I'm facing a similar issue, although it might be due to my language setting. Dark mode is completely broken and I don't see any of the other features working.
![image](https://user-images.githubusercontent.com/55856800/214980248-5f7ad5ef-453b-40ac-aded-81f9d6eafc54.png)

**Comment by ksucpea** [comment]
Most of the features available require you to be in the card view not the
list view like you are, but I’m not sure why the dark mode is broken like
that. Do you know how to inspect element and find the white parts? If you
can, send a screenshot of the inspect element or if you don’t I can tell
you how to. Thanks

**Comment by probablypablito** [comment]
Card view seems to have fixed the issue not showing. This is great! 

I don't mind the dark mode too much. I can inspect element whatever you want but I'm  not sure which white part to select :P

I can send you a downloaded version of my page if you'd like, but I'd like it to be kept private for privacy concerns.

**Comment by ksucpea** [comment]
Awesome, maybe screenshot like 2 or 3 of the white elements so I can see if
I can spot an issue

**Comment by ksucpea** [comment]
If you don’t know which elements are the white ones just right click in the
general area of the white element and inspect it and try to find an element
that has background-color: #fff or something similar as one of the styles

**Comment by probablypablito** [comment]
I'd rather send the HTML, I just finished a project involving heavy JS / inspect elementing and do not want to use it any more. Let me know a good way to contact you. You can email me at github [AT] pablito.tech

**Comment by ksucpea** [comment]
Alright, you can email me ksucpea@gmail.com
