### ISSUE TITLE
Does not work with multiple Canvas Domains

### ISSUE THREAD

**Issue by evanspielvogel** [ksucpea/bettercanvas#16]
I am a student that is in a program where I am enrolled in two schools and as such have two canvas domains. Is there a way to have Better Canvas work on multiple domains?

**Comment by ksucpea** [comment]
What domains are they? You could get it to work if one of them contains canvas, instructure, learn, or school in it

**Comment by ksucpea** [comment]
I just updated the extension so you can now add multiple domains by separating them with a comma in the custom url inout, for example "https://url1.com, https://url2.com"
