### ISSUE TITLE
Improved Todo list does not respect language time format

### ISSUE THREAD

**Issue by jojo2357** [ksucpea/bettercanvas#19]
I have English (UK) set for my canvas specifically to have 24-hour time, and the improved todo tab does not respect this

As seen from todo:
![image](https://user-images.githubusercontent.com/66704796/214500975-83c91426-b8fa-4766-bd97-1d4540d5709b.png)

As seen from assignment:
![image](https://user-images.githubusercontent.com/66704796/214501052-ec0443f4-6dc9-4aa4-8b59-611e8eea878a.png)

Also, the ability to set 24 hour time independently of language would be huge.

**Comment by ksucpea** [comment]
Thanks for bringing this up, I never even thought about this. I'll look into implementing it later today.

**Comment by ksucpea** [comment]
Alright, I added an option to enable 24 hr format in the menu. I will post the update within the next few days probably. Thanks for the suggestion

**Comment by jojo2357** [comment]
I use firefox, could that branch get the update too?

**Comment by ksucpea** [comment]
Yeah I can do that, I just need to fix some things first for both versions. The Firefox version will probably be updated today anyway because their reviews are almost instant, but chrome takes a bit.

**Comment by jojo2357** [comment]
Also, would it be possible to set a global time format (without changing the language?) Looking at the commits *seems* plausible, but the todo list is created by the plugin whereas the others are not which can be problematic.

Thanks for the quick fixes :)

**Comment by ksucpea** [comment]
I think I could add this, but I'm not exactly sure how I'd do it. Do you mean like scan the page for dates and change am/pm to 24hr format?

**Comment by jojo2357** [comment]
![image](https://user-images.githubusercontent.com/66704796/214696999-90d1f4cb-07e1-4fbc-a9c1-5dc3b9f8de28.png)

It looks plausible to find these tags and change them. I dont see an attached event listening to `format` changing unfortunately. Still looks very parse-able in this example

**Comment by jojo2357** [comment]
Nevermind, that was just a single example. on my assignments tab, there is a different strategy 
![image](https://user-images.githubusercontent.com/66704796/214697787-c98fd285-40dd-4c50-84ff-a87af8a5c1b4.png)

**Comment by ksucpea** [comment]
I will see what I can do but I probably won't be adding that feature if you can change the language to get the 24hr time instead. Also the update is out on Firefox, you'll probably have to press the check for updates button in the addons menu to get the update. Let me know if you have any issues with it, thanks
