### ISSUE TITLE
Left sidebar does not follow dark mode

### ISSUE THREAD

**Issue by colin4683** [ksucpea/bettercanvas#20]
The left sidebar tab needs to follow the dark theme
![image](https://user-images.githubusercontent.com/38335987/221680984-2060e16c-aecd-4748-a45c-7c61ec8b2004.png)

**Comment by ksucpea** [comment]
Do you know what the css selector is for that sidebar? It's still dark for me so I don't know how to find it on my end

**Comment by colin4683** [comment]
> Do you know what the css selector is for that sidebar? It's still dark for me so I don't know how to find it on my end

![image](https://user-images.githubusercontent.com/38335987/222927748-e83208b0-aacf-4170-bf13-347d623df227.png)

**Comment by ksucpea** [comment]
Sorry it's been so long, been really busy lately. I added the selector in the most recent update, it's out on Firefox now but might take a day or two for Chrome. Please let me know if it didn't fix
