### ISSUE TITLE
[SUGGESTION] Full-screen being limited to the window whe previewing documents.

### ISSUE THREAD

**Issue by sealldeveloper** [ksucpea/bettercanvas#21]
I've always had a bit of a gripe with the fullscreen preview being an entire fullscreen and not just a window fullscreen, still displaying the top bar.

(Note: I'm the reviewer asking for custom images and names stored localled :D)

**Comment by ksucpea** [comment]
Not really sure if I can do anything about that but I'll do some testing. Also I have gotten your other suggestion to work, just need to fix some issues first. I'll probably have that update out next week
