### ISSUE TITLE
Dark Mode doesn't effect colours inside table cells

### ISSUE THREAD

**Issue by sealldeveloper** [ksucpea/bettercanvas#23]
Colours of the cells doesn't get adjusted by darkmode, while the text does. Some text also doesn't seem to invert?

With Dark Mode:
![image](https://user-images.githubusercontent.com/120470330/226312133-d68c291e-d229-4da7-9daf-130e7ab00306.png)

Without:
![image](https://user-images.githubusercontent.com/120470330/226312201-a4988ef0-0082-42bb-afc7-6d74c9b975db.png)

**Comment by ksucpea** [comment]
Not sure I can do anything about this since it's blue, do you know the css selectors for the table?

**Comment by sealldeveloper** [comment]
Table: `border-collapse: collapse; width: 97.8968%; background-color: #c2e0f4; border-color: #000000; border-style: solid; margin-left: auto; margin-right: auto; height: 1965px;`
td: `width: 5.79635%; background-color: #236fa1; text-align: center; height: 197px;`

**Comment by sealldeveloper** [comment]
No real selectors...

**Comment by ksucpea** [comment]
Hmm, well in this case I would suggest turning dark mode off when this happens so you can see the text
