### ISSUE TITLE
Tile List

### ISSUE THREAD

**Issue by iiDaxter** [ksucpea/bettercanvas#24]
Hello,

For some reason my tile list is not working. Have tried on multiple devices / browsers.

Here is a video I uploaded as well. 

[https://imgur.com/a/piTElnz]

Thanks.

**Comment by ksucpea** [comment]
There seems to be some difference between my school's canvas and everyone elses canvas, so the way I created it only works for my version and isn't working for anyone else. I have an update coming out shortly to fix this... chrome store is just taking really long to update.

**Comment by iiDaxter** [comment]
It was working fine for weeks this just started happening today.

**Comment by ksucpea** [comment]
Yeah, to clarify I mean in the most recent update a few days ago I made it that way. I had to rework some things and changed how the assignments load, but it only works for me.

**Comment by iiDaxter** [comment]
Okay cool if you ever want to troubleshoot with my account my Discord is Daxter#0001

**Comment by ksucpea** [comment]
Update is out now, let me know if you encounter any issues, thanks 👍

**Comment by iiDaxter** [comment]
Works like a charm, thank you!
