### ISSUE TITLE
Allow customisation of grade boundries

### ISSUE THREAD

**Issue by ZachLiamBarrett** [ksucpea/bettercanvas#25]
Hello, my university uses a slightly different grading schedule, because of that my calculated GPA is different to its true value. It would be great if I could adjust the grade boundaries to reflect my universities marking schedule.

**Comment by ksucpea** [comment]
Gotcha, I’ll see if I can add this. What gpa system does your university
use?

**Comment by ZachLiamBarrett** [comment]
Im not sure it uses any specific system, but here is the marking schedule:
https://student.aut.ac.nz/study/study-help/assessments-and-exams/assessment-results-and-paper-grading

**Comment by ksucpea** [comment]
Added this in the new update. Not sure when I'll publish it to the Chrome store because I'm still working on it, but you can download the extension manually and install it if you'd like to test

**Comment by ksucpea** [comment]
Live on firefox now, chrome will be updated shortly
