### ISSUE TITLE
Dashboard card color overlay allways on.

### ISSUE THREAD

**Issue by tibogeeraerts** [ksucpea/bettercanvas#26]
Hi, 
I changed the dashboard card images to custom images. When I open my Canvas, it always has the color overlay on. It would be nice to turn off color overlay in the extension menu. I want to contribute to this if possible.

**Comment by ksucpea** [comment]
There should already be an option to disable color overlay in Canvas. There's 3 dots next to the dashboard text at the top that opens a menu with the option. Let me know if you can't find it

**Comment by tibogeeraerts** [comment]
I know that Cancas has this option but it doesn't always seem to work very well. I have done my best to program a solution to this problem and opend a pull request. You can do what you want with the solution.
