### ISSUE TITLE
Better Canvas changes the style sheet of other sites when the canvas URL is not set

### ISSUE THREAD

**Issue by Sophon96** [ksucpea/bettercanvas#31]
Just installed Firefox, synced my extensions, and found all the websites looking odd. After disabling all my extensions, I found that Better Canvas seemed to be the culprit. Setting the Canvas URL in the options menu fixes it.
Here are a few examples of what happens:
### GitHub
Unset Canvas URL (odd-looking): 
![image](https://github.com/ksucpea/bettercanvas/assets/71684640/5dcbdb6a-617d-4586-a707-dd32729a0baa)
Set Canvas URL (correct): 
![image](https://github.com/ksucpea/bettercanvas/assets/71684640/486beb88-39ce-4678-8368-a39cfb8a6a1e)

### Google
Unset Canvas URL:
![image](https://github.com/ksucpea/bettercanvas/assets/71684640/59783982-c25d-4def-a557-8f761e6f31af)

Set Canvas URL:
![image](https://github.com/ksucpea/bettercanvas/assets/71684640/20c0acb7-b9e1-4f40-9ea4-9a6c35f75870)

**Comment by ksucpea** [comment]
What extension version is this? I just updated the extension a few minutes
ago and I changed some things with the url stuff so I might need to fix
that

**Comment by Sophon96** [comment]
5.7.1

**Comment by ksucpea** [comment]
Ok cool, should be fixed now, thanks for letting me know about this

**Comment by Sophon96** [comment]
Fixed!
