### ISSUE TITLE
Text Boxes are unreadable in dark mode

### ISSUE THREAD

**Issue by Saragon4005** [ksucpea/bettercanvas#32]
the CSS found in https://du11hjcvx0uqb.cloudfront.net/dist/brandable_css/new_styles_normal_contrast/bundles/what_gets_loaded_inside_the_tinymce_editor-a64c7fe33c.css needs to be inverted so its not black text on dark backround.

**Comment by ksucpea** [comment]
Do you know what selector specifically needs to be changed? There seems to be a lot in there.

**Comment by Saragon4005** [comment]
It should be --ic-brand-font-color-dark

**Comment by ksucpea** [comment]
Gotcha, I'll include these changes in the next update. If you want I can give you instructions on how to update the dark mode manually right now.
