### ISSUE TITLE
limit text area resizing

### ISSUE THREAD

**Issue by bronwyncombs** [ksucpea/bettercanvas#36]
notes box resizes into side panel and gets stuck:

https://github.com/ksucpea/bettercanvas/assets/135047322/872aad8b-3623-4f17-96aa-1468a41c2d0c

i'm not a dev but i just saw a similar fix using this:

`<[&_textarea]:resize-y">`

i tested and it worked! 

<img width="253" alt="Screenshot 2023-10-06 at 9 14 41 PM" src="https://github.com/ksucpea/bettercanvas/assets/135047322/aa439b30-7e40-4e8a-8a4e-d61d27b689e4">

https://github.com/ksucpea/bettercanvas/assets/135047322/63d39f64-0247-49b0-bc54-d2f9d9e96a48

**Comment by ksucpea** [comment]
Looks good to me, I'll include it in the next update. Thanks 👍
