### ISSUE TITLE
[Feature request] Individual gradients per class

### ISSUE THREAD

**Issue by a11ce** [ksucpea/bettercanvas#37]
Currently it is only possible to set all classes to display with the same gradient. I would like a way to set each class to have its own gradient.

**Comment by ksucpea** [comment]
I'm not too sure what you mean by the same gradient, but the gradients are calculated based on the color that the image has, so you can change the gradient by changing the color of the card in the top right corner of each card (note you may have to toggle the gradients off and on again in the menu to see the changes).

**Comment by a11ce** [comment]
Got it, thank you.
