### ISSUE TITLE
Modules turn white when hovered over with mouse (dark mode enabled)

### ISSUE THREAD

**Issue by NintwnDude879** [ksucpea/bettercanvas#38]
https://drive.google.com/file/d/1-dyCMRiEsQdhE0_6h93qv6Hs35-Oyh1G/view?usp=sharing

**Comment by NintwnDude879** [comment]
If it helps at all, it seems like this color is contained in content_next-b97782a268.css (the numbers/letters could be random, I'm unsure), with ".context_module_item.context_module_item_hover"s background being set to a hex color.
Code snippet (beautified cus it's all on one line otherwise):
`.context_module_item.context_module_item_hover {
  background: #fff;
}`

**Comment by ksucpea** [comment]
Thanks for pointing this out. I'll try fixing it and include it in the next update.
