### ISSUE TITLE
Previous hovering issue with modules still not fixed

### ISSUE THREAD

**Issue by NintwnDude879** [ksucpea/bettercanvas#40]
Completely unsure of where the styling is being done for the modules, but they still turn white when hovered over. 

https://drive.google.com/file/d/1XHp6rayROAbk5x83nKdJ_BuUsyGht2B-/view?usp=sharing

**Comment by NintwnDude879** [comment]
This seems to be the issue, but when I change the color it's trying to display, it still doesn't change.

https://drive.google.com/file/d/1JD6Tk3pdwQ3SmJezcIN0vXgEvETNzw9F/view?usp=sharing

**Comment by ksucpea** [comment]
I haven't published the update yet but I'll let you know when I do.

**Comment by ksucpea** [comment]
Should be fixed in 5.8.8 (please let me know again if it isn't) Sorry it's been a while, I've been focused on other things and was extremely busy with school.
