### ISSUE TITLE
"Upload media" (when submitting assignments & when uploading media comments) is not dark in dark mode

### ISSUE THREAD

**Issue by NintwnDude879** [ksucpea/bettercanvas#43]
![Screenshot 2023-10-26 182350](https://github.com/ksucpea/bettercanvas/assets/62903324/78646b0a-ed30-4a0d-8c22-1e24b4edc377)

Didn't want to doxx myself so I didn't screenshot outside of the box, but the rest of the page gets enveloped in a partially-transparent white color when you open up this menu for uploading a media comment

**Comment by ksucpea** [comment]
Where could I find this? When I try to upload something for an assignment I don't get a similar prompt.
