### ISSUE TITLE
Thank you @ksucpea!!!

### ISSUE THREAD

**Issue by microbearsmb** [ksucpea/bettercanvas#47]
I know this isn't what issues are for, so feel free to delete this if you like. I just wanted to express my gratitude to @ksucpea and the rest of the dev community for this project; I was delighted to find something like this for my school's LMS. I am so excited to use Canvas now with these features, and I anticipate my productivity increasing because of it!

microbearsmb

**Comment by ksucpea** [comment]
I really appreciate your support! Enjoy 👍
