### ISSUE TITLE
[Feature / bug(?)] Todo list doesn't include past due assignments

### ISSUE THREAD

**Issue by probablypablito** [ksucpea/bettercanvas#48]
Thanks for this extension!

The current to-do list below each class' doesn't include incomplete assignments that are past due.. Judging by the [source code](https://github.com/ksucpea/bettercanvas/blob/97c6921d138ac764d401681b79bbb0b869fcf7f8/js/content.js#L853C40-L853C44) this seems to be intentional, but is quite annoying. Could a toggle be added?

**Comment by ksucpea** [comment]
Sorry for getting back so late, this will be in the next update (just submitted it, might take a bit for it to update on chrome)

**Comment by ksucpea** [comment]
Just a heads up you might have to manually update the extension or reinstall it to get the update. I only pushed it to about 1% of users and will be bringing that up once I confirm that there's no bugs, so you probably won't get updated automatically.

**Comment by probablypablito** [comment]
Got it, I was using a fork temporarily while this got (properly) implemented.
