### ISSUE TITLE
Some elements aren't dark mode

### ISSUE THREAD

**Issue by cartler-ctrl** [ksucpea/bettercanvas#5]
I'd also like to mention the eye straining white on some of the large submission buttons

Chrome version:

![Screenshot 2022-01-11 10 14 41 AM](https://user-images.githubusercontent.com/79550882/148980062-815735bb-082c-4860-aa39-727d79b68bc2.png)

**Comment by ksucpea** [comment]
Thanks for bringing this up. What's the url for this page? I'm looking at instructure.com/courses/<course id>/assignments but my assignments page looks different than yours so I may be looking at the wrong thing.

**Comment by cartler-ctrl** [comment]
Yup, same url.

I think that teachers can choose different assignment formats.

**Comment by ksucpea** [comment]
Hmm, well I think the only way I could fix this is if you inspect element and find the styles for the white elements on this page. If you'd like to help me out I can show you how to find them.  I have access to a teacher account and don't know how to make an assignment appear like how yours is appearing so I can't really fix it on my end.
