### ISSUE TITLE
[Feature Request] Colorized to-do list items

### ISSUE THREAD

**Issue by kh2310** [ksucpea/bettercanvas#51]
This is a pretty minor feature, but it would be cool to have the option to color-code the titles of to-do list items to correspond with their respective class colors. [Here's an example of what it could look like](https://i.postimg.cc/6pDwvrgg/Screenshot-2024-01-17-at-22-42-24-Dashboard.png). This would make it a little easier to see what classes you need to focus on at a glance, and I also think it'd look nice

**Comment by ksucpea** [comment]
Thanks for the suggestion, I'll look into this

**Comment by ksucpea** [comment]
I added this in the new update, it's available on Firefox right now if you want to try it out 👍

**Comment by HugoKim36** [comment]
It looks great, thanks for adding this!
