### ISSUE TITLE
Better Todo List max height hides due dates of long classes

### ISSUE THREAD

**Issue by FireIsGood** [ksucpea/bettercanvas#53]
## Problem

When using the Better Todos options, the due date for classes can be hidden due to the class name being too long. This can be an issue stopping users from using it, as the default todo list does not have this limitation.

![Long title that is clipped](https://github.com/ksucpea/bettercanvas/assets/109556932/6035e354-e276-4087-a9fe-478f8c87daaf)

## Cause

I have found in the CSS that it is caused by an injected style on the `.bettercanvas-todo-container` which adds a `max-height: 100px`.

![image](https://github.com/ksucpea/bettercanvas/assets/109556932/3ce7e805-7e14-44dc-aa7c-6a3fe49d8785)

## Solution

Using a user style, I have been able to fix the issue by simply setting a `max-height: unset`. To fix this here, the `max-height` style should be removed.

![image](https://github.com/ksucpea/bettercanvas/assets/109556932/58bca8d1-c888-4d9b-8161-706e035e89de)

**Comment by ksucpea** [comment]
Good catch, I'm not sure why I added that
