### ISSUE TITLE
Subtitle text really hard to read in dark mode

### ISSUE THREAD

**Issue by TheVanadium** [ksucpea/bettercanvas#56]
![image](https://github.com/ksucpea/bettercanvas/assets/53013571/e6d265ad-eeb8-4fd9-8eb9-ab4422c6a106)
The dark gray text under each bright blue line (except the first) is really difficult to read. I think the dark mode should allow these kinds of things to be visible. On my canvas portal, the text is supposed to describe which semester the course is in.

Light mode visibility for reference:
![image](https://github.com/ksucpea/bettercanvas/assets/53013571/f1006ea7-bc77-40d8-93b5-f3faa7d2d78e)

**Comment by ksucpea** [comment]
I fixed the course semester text but i'm not sure what page is in the background (if that is also what you're requesting to be fixed). Could you let me know?
