### ISSUE TITLE
[Feature request] To Do tags

### ISSUE THREAD

**Issue by aelew** [ksucpea/bettercanvas#59]
It would be really nice if there was some sort of tag system for labeling assignments in the to-do list. Some of my professors like to create assignments for purely informational announcements, so this would be pretty useful in identifying which assignments are actual stuff I would need to get done without clicking on each individual item.

**Comment by ksucpea** [comment]
Thanks for the suggestion - I added this in the new update, it's available on Firefox right now if you want to try it out 👍 You'll have to click the three dots next to an item in the todo list to set a label
