### ISSUE TITLE
[Feature Request] Using locally downloaded fonts as custom fonts

### ISSUE THREAD

**Issue by gunacorn** [ksucpea/bettercanvas#62]
As of right now, the only custom fonts we can set are fonts that are available through Google Fonts. It would be great if we would also use locally downloaded fonts as custom fonts.

**Comment by ksucpea** [comment]
I'm not entirely sure if this is possible unless I were to request filesystem permissions which I would prefer not to do. I also don't think it's possible to save a font file into local storage either, so unfortunately I don't think I can add this
