### ISSUE TITLE
[Feature Request] Color-Coded Favicons 

### ISSUE THREAD

**Issue by kh2310** [ksucpea/bettercanvas#63]
It would be very helpful if this extension could color-code the favicons for different course pages (and sub-pages) to match each course's color theme. I spend a lot of time with a ton of Canvas tabs open, and sometimes it can be hard to navigate through all my open tabs. Color-coding the favicons would make it way easier to tell which course pages I have open at a glance

Example of how this could look:

![tabtest](https://github.com/ksucpea/bettercanvas/assets/160697135/006f8733-4061-41b9-9c55-16e76d04d107)

**Comment by ksucpea** [comment]
Thanks for the suggestion - I added this in the new update, it's available on Firefox right now if you want to try it out 👍

**Comment by HugoKim36** [comment]
So far, looks great!

There's only one minor bug—for some reason, I see the default favicons if I right click on a Canvas link to open it in a new tab (but it works if I refresh the page afterwards, or if I navigate through Canvas in one tab). But other than that, it works perfectly
