### ISSUE TITLE
Request: Code of Conduct

### ISSUE THREAD

**Issue by laignelet16** [ksucpea/bettercanvas#65]
Hello! I am interested in participating in this open-source project! As I was learning about the development environment by reading through the contributing file, I noticed there was no code of conduct file on the Github repo. Is it possible to create a code of conduct on the Github repo that establishes expectations for behavior for the project’s participants? If so, I would like to contribute to this suggestion. Thank you!

**Comment by ksucpea** [comment]
Hi there, are you requesting me to create a code of conduct so that you can contribute or would you like to contribute by creating a code of conduct?

**Comment by laignelet16** [comment]
I would like to contribute by creating a code of conduct if it is possible!

**Comment by ksucpea** [comment]
Yeah that's totally cool with me!
