### ISSUE TITLE
Fix for dashboard grades not showing

### ISSUE THREAD

**Issue by August-H** [ksucpea/bettercanvas#67]
getGrades function takes from current_grading_period scores when it should be computed_current_score

Fixed getGrades funciton:

function getGrades() {
    if (options.gpa_calc === true || options.dashboard_grades === true) {
        grades = getData(`${domain}/api/v1/courses?enrollment_state=active&include[]=concluded&include[]=total_scores&include[]=computed_current_score&per_page=100`);
    }
}

Line 1778 in content.js
Fixes GPA calculator also

**Comment by August-H** [comment]
![Screenshot 2024-04-28 151500](https://github.com/ksucpea/bettercanvas/assets/140870788/9e6bbdc0-c82b-4dd3-9265-b551c9cf7e0d)

Bug in red

**Comment by ksucpea** [comment]
Sorry for the extremely late response, been quite busy. I'll try getting this into the next update whenever that is (maybe in a month or two)
