### ISSUE TITLE
Past Courses under Card Customization is blank / No way to retrieve previous URLs used for backgrounds

### ISSUE THREAD

**Issue by Bobby-ct** [ksucpea/bettercanvas#69]
No Past Courses show up while in Card Customization settings, only the header "Past Courses" (id="advanced-past")
This past school year was the first time I used Better Canvas and was looking forward to reusing the background images I had set on my past class cards- but now that I went to go look at the past course settings in Better Canvas, I found it to be blank.  Not a serious issue or anything, just kinda annoying that I'll have to go back and try to find the same links that I used before.  
![Screenshot 2024-06-13 213302](https://github.com/ksucpea/bettercanvas/assets/121133868/097aa45d-b62f-42b2-9eb8-7fee707890e8)

**Comment by ksucpea** [comment]
I think this this could be happening if your past courses are now marked as inactive. If you go to https://<your canvas url>/courses, do the classes show up under "Past Enrollments"?

**Comment by Bobby-ct** [comment]
All of my courses from the past school year show up under Past Enrollments on the actual canvas page itself, its just the plugin that doesn't recognize any of them
![Screenshot 2024-06-17 233012](https://github.com/ksucpea/bettercanvas/assets/121133868/94da4bdb-407f-4df5-a936-8707be1054e9)

**Comment by ksucpea** [comment]
I see, I'll try changing it to include inactive classes then

**Comment by ksucpea** [comment]
I've been trying to get my past enrollments to show up but I'm not sure how to do it. I thought removing the active indication from the enrollment state would include inactive classes, but it doesn't. Also setting the state to available + completed doesn't include past enrollments either. Unfortunately this might not be possible to fix
