### ISSUE TITLE
"Dashboard view" not in darkmode

### ISSUE THREAD

**Issue by KwiiHours** [ksucpea/bettercanvas#7]
The "dashboard view" dropdown menu doesn't display in darkmode (see [here](https://media.discordapp.net/attachments/590667063165583409/956474809024413716/unknown.png))

Playing around with the CSS, it looks like it gets its attributes from
 `--sJGfW-labelColor `
`--sJGfW-activeBackground`
`--dqmEK-arrowBackgroundColor`
`--sJGfW-background`

**Comment by ksucpea** [comment]
Fixed it, thanks for letting me know about this
