### ISSUE TITLE
Theme doesn't apply to sets

### ISSUE THREAD

**Issue by bruhderek** [ksucpea/bettercanvas#70]
<img width="2021" alt="image" src="https://github.com/ksucpea/bettercanvas/assets/84210066/70c47630-8092-49fa-afcc-c171505822ec">

**Comment by ksucpea** [comment]
Does the dark mode fixer in the edit dark mode tab help at all?

**Comment by bruhderek** [comment]
@ksucpea It doesn't help

**Comment by ksucpea** [comment]
Ok, I think I could fix the sidebar if you can find out the css selector for it, but I doubt I could fix the triangle since that's probably an image
