### ISSUE TITLE
Safari Extension?

### ISSUE THREAD

**Issue by Pranav-Karra-3301** [ksucpea/bettercanvas#72]
Any Plans to extend this extension to be supported on safari?

**Comment by ksucpea** [comment]
Not at the moment, I don't have a mac so I can't access xcode to port the extension to safari

**Comment by wolfiediscord** [comment]
I saw this extension being used by one of my colleagues, so I decided to try it out on Safari by using Xcode's safari-web-extension-converter. It took a few builds, but it seems to work pretty well. 

There are some bugs that I have spotted straight away, like one of my classes has a blank icon that doesn't do anything. 
![Screenshot 2024-09-11 at 15 05 35](https://github.com/user-attachments/assets/ad626c19-97fc-4912-95ee-f94a5178b359)

Also, some of the menus are cut off or nonfunctional, like the dashboard has some white space. The Cards button and GPA buttons break the extension, requiring you to click out of the menu and re-click into the menu. 

_Dashboard_
![Screenshot 2024-09-11 at 15 14 03](https://github.com/user-attachments/assets/401dce61-c8aa-4f9d-8913-54a918f73fe8)

_Cards View_
![Screenshot 2024-09-11 at 15 15 25](https://github.com/user-attachments/assets/7d6c437e-e39f-446b-82c3-64a3e14ed52b)

_GPA View_
![Screenshot 2024-09-11 at 15 15 43](https://github.com/user-attachments/assets/e8e6d1d0-fabd-4923-b3ae-3230a5429073)

I'd imagine it would probably require a Apple Developer account to upload to the App Store, which is expensive in comparison to Google Chrome or Firefox, but it's nice to see that it works pretty flawlessly. I don't expect for you to make a Safari extension, I just wanted to see if it was even possible.

**Comment by ksucpea** [comment]
Yeah, I just don't think it's worth having a developer account, plus I don't have a mac anyway. Firefox is free and Chrome had a one time fee of $5 lol. I'd just recommend for anyone else to get Chrome, since you mentioned it looks like it has some issues on Safari, or if you really want to use Safari you can port the extension over manually but I will not be hosting an official safari version anywhere.
