### ISSUE TITLE
Add-On No Longer Functioning

### ISSUE THREAD

**Issue by Cup-of-Joe-P** [ksucpea/bettercanvas#76]
Hey! I'm sure I'm just missing something silly but I can't figure out what's wrong, so I could use some help.

The add-on was functioning fine for me for a while but suddenly it stopped having any influence on UTSA Canvas.
I don't believe there was any notable change with my Firefox client that could have affected Better Canvas.

I've made sure the add-on can read data on all sites, as well as explicitly allowing permission for utsa.instructure.com in Mozilla settings. I have also added the Canvas link within the add-ons internal settings.
Despite this, the add-on makes no changes to UTSA canvas while providing no error messages (at least none that are obviously connected to Better Canvas).

If there's any other information you need, please let me know, and thanks!

**Comment by ksucpea** [comment]
Sorry for the late response, if you press Ctrl + Shift + J (or Cmd + Shift + J on a Mac) does it say "Better Canvas - running" anywhere?

**Comment by Cup-of-Joe-P** [comment]
No problem at all, I appreciate the response! It doesn't look like there's anything related to Better Canvas running in the multiprocess console. I take it this means that there's something I need to enable?

**Comment by ksucpea** [comment]
That's strange, usually this happens when there's an issue with the url set in the menu if nothing is running, but it sounds like you set it properly. Could you send the exact url you set in the better canvas menu?

**Comment by Cup-of-Joe-P** [comment]
Sure thing!
https://utsa.instructure.com/
I've also tried without the https prefix but there's no change when I do.

**Comment by Cup-of-Joe-P** [comment]
Fixed it! For some reason removing the add-on and completely reinstalling Firefox on my laptop fixed the issue across all of my devices, including my laptop upon reinstallation of the add-on. No idea what could have possibly been the problem or how a reinstall that changed no settings would have fixed it, but I'll take it!
