### ISSUE TITLE
Grades don't show up

### ISSUE THREAD

**Issue by Globalfun32y439y54** [ksucpea/bettercanvas#89]
I have grades in the second grading period and Better Canvas does not show to grade for the period

**Comment by ksucpea** [comment]
Hm, thought this was fixed a while ago by someone else. Can you go to "https://<your canvas url>/api/v1/courses?include[]=concluded&include[]=total_scores&include[]=current_grading_period_scores&per_page=100" and let me know if you can find your current grades in there (with ctrl+f search)? If it is in there, is it under "current_period_computed_current_score"?
![image](https://github.com/user-attachments/assets/2cabf1e6-64b7-45a2-b638-e623e787e713)

**Comment by Globalfun32y439y54** [comment]
This it what it says:
![image](https://github.com/user-attachments/assets/37b90f0c-de54-44f3-ae83-da53cf48d0a2)

This is what better canvas:
![image](https://github.com/user-attachments/assets/fbf2d43c-5200-4db6-be92-e6caac2b42ee)

**Comment by Globalfun32y439y54** [comment]
yes

**Comment by Globalfun32y439y54** [comment]
Fixed
