### ISSUE TITLE
Add quizzes to dashboard view

### ISSUE THREAD

**Issue by pkoos** [ksucpea/bettercanvas#9]
Currently, there is an option for Dashboard Assignments. Would it be possible to add one for Dashboard Quizzes as well?

**Comment by ksucpea** [comment]
I'm pretty sure the assignments include quizzes but I may be wrong. Are quizzes not showing up for you?

**Comment by pkoos** [comment]
No they do not. Here is the quiz view for one of my classes: 
![image](https://user-images.githubusercontent.com/7260843/164771975-d7cb4eba-7503-4259-bcad-d6bfbff54d61.png)

And here is the dashboard: 
![image](https://user-images.githubusercontent.com/7260843/164772054-22970dd1-f88a-419b-af96-a76831fc1d49.png)

Sometimes my professors use the quiz infrastructure for assignments, and they don't appear for me in the dashboard.

**Comment by ksucpea** [comment]
I see, I will work on this and try to add quizzes to the list instead of making a separate toggle

**Comment by ksucpea** [comment]
Got quizzes to show up in the list, will be included in the next update. thanks for the suggestion!
